; PlatformIO Project Configuration File
;
; VoC Monitor - ESP8266 (NodeMCU)
;

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps = 
    olikraus/U8g2@^2.35.0
    adafruit/Adafruit AHTX0@^2.0.3
    sparkfun/SparkFun Indoor Air Quality Sensor - ENS160@^1.0.0
    bblanchon/ArduinoJson@^6.21.0

build_flags = 
    -DCORE_DEBUG_LEVEL=3