; PlatformIO Project Configuration File
;
; ESP8266 + ILI9341 2.2" TFT VoC Monitor
;

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Library dependencies - using Adafruit ILI9341
lib_deps = 
    adafruit/Adafruit GFX Library@^1.11.0
    adafruit/Adafruit ILI9341@^1.6.0
    adafruit/Adafruit BusIO@^1.14.0

build_flags = 
    -D PIO_FRAMEWORK_ARDUINO_LWIP2_LOW_MEMORY